export const CACHE_TTL = {
  NOTES_LIST: 300,
  NOTES_TRENDING: 600,
  NOTES_SEARCH: 30,
  NOTE_DETAIL: 120,
  RESOURCES_LIST: 300,
  RESOURCES_TRENDING: 600,
  RESOURCE_DETAIL: 120,
  ACTIVITY: 30,
  LEADERBOARD: 300,
  USER_PROFILE: 120,
  ADMIN_STATS: 300,
  ADMIN_ACTIVE_USERS: 120,
  ADMIN_REPORT: 300,
  ADMIN_SETTING: 60,
  ADMIN_PERMISSIONS: 60,
  ANALYTICS: 120,
};

export const PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 12,
  MAX_LIMIT: 100,
  NOTIFICATIONS_LIMIT: 20,
  USERS_LIMIT: 20,
};

export const TOP_N = {
  LEADERBOARD: 30,
  TRENDING_NOTES: 10,
  TRENDING_RESOURCES: 10,
  POPULAR_NOTES: 10,
  TOP_USERS: 10,
  MOST_ACTIVE_USERS: 20,
};

export const ANALYTICS = {
  WINDOW_7_DAYS: 7,
  WINDOW_30_DAYS: 30,
  WINDOW_90_DAYS: 90,
  ACTIVE_USER_MINUTES: 5,
};

export const OTHER = {
  NOTIFICATION_RETENTION_DAYS: 30,
  LEADERBOARD_POINTS_THRESHOLD: 500,
  POINTS_PER_DOWNLOAD: 1,
  POINTS_PER_NOTE_APPROVAL: 10,
  REDIS_RETRY_MAX_ATTEMPTS: 10,
  REDIS_RETRY_BASE_MS: 100,
  REDIS_RETRY_MAX_MS: 5000,
  REDIS_SCAN_COUNT: 100,
};
